/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ProRouteImport } from './routes/pro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as R500RouteImport } from './routes/500'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user.index'
import { Route as ProIndexRouteImport } from './routes/pro.index'
import { Route as UserReviewsRouteImport } from './routes/user.reviews'
import { Route as UserProfileRouteImport } from './routes/user.profile'
import { Route as UserNotificationsRouteImport } from './routes/user.notifications'
import { Route as UserBookingsRouteImport } from './routes/user.bookings'
import { Route as ServiceIdRouteImport } from './routes/service.$id'
import { Route as ProviderIdRouteImport } from './routes/provider.$id'
import { Route as ProServicesRouteImport } from './routes/pro.services'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const ProIndexRoute = ProIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProRoute,
} as any)
const UserReviewsRoute = UserReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserNotificationsRoute = UserNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => UserRoute,
} as any)
const UserBookingsRoute = UserBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => UserRoute,
} as any)
const ServiceIdRoute = ServiceIdRouteImport.update({
  id: '/service/$id',
  path: '/service/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIdRoute = ProviderIdRouteImport.update({
  id: '/provider/$id',
  path: '/provider/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProServicesRoute = ProServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ProRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/500': typeof R500Route
  '/login': typeof LoginRoute
  '/pro': typeof ProRouteWithChildren
  '/providers': typeof ProvidersRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/user': typeof UserRouteWithChildren
  '/pro/services': typeof ProServicesRoute
  '/provider/$id': typeof ProviderIdRoute
  '/service/$id': typeof ServiceIdRoute
  '/user/bookings': typeof UserBookingsRoute
  '/user/notifications': typeof UserNotificationsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/reviews': typeof UserReviewsRoute
  '/pro/': typeof ProIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/500': typeof R500Route
  '/login': typeof LoginRoute
  '/providers': typeof ProvidersRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/pro/services': typeof ProServicesRoute
  '/provider/$id': typeof ProviderIdRoute
  '/service/$id': typeof ServiceIdRoute
  '/user/bookings': typeof UserBookingsRoute
  '/user/notifications': typeof UserNotificationsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/reviews': typeof UserReviewsRoute
  '/pro': typeof ProIndexRoute
  '/user': typeof UserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/500': typeof R500Route
  '/login': typeof LoginRoute
  '/pro': typeof ProRouteWithChildren
  '/providers': typeof ProvidersRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/user': typeof UserRouteWithChildren
  '/pro/services': typeof ProServicesRoute
  '/provider/$id': typeof ProviderIdRoute
  '/service/$id': typeof ServiceIdRoute
  '/user/bookings': typeof UserBookingsRoute
  '/user/notifications': typeof UserNotificationsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/reviews': typeof UserReviewsRoute
  '/pro/': typeof ProIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/500'
    | '/login'
    | '/pro'
    | '/providers'
    | '/register'
    | '/services'
    | '/user'
    | '/pro/services'
    | '/provider/$id'
    | '/service/$id'
    | '/user/bookings'
    | '/user/notifications'
    | '/user/profile'
    | '/user/reviews'
    | '/pro/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/500'
    | '/login'
    | '/providers'
    | '/register'
    | '/services'
    | '/pro/services'
    | '/provider/$id'
    | '/service/$id'
    | '/user/bookings'
    | '/user/notifications'
    | '/user/profile'
    | '/user/reviews'
    | '/pro'
    | '/user'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/500'
    | '/login'
    | '/pro'
    | '/providers'
    | '/register'
    | '/services'
    | '/user'
    | '/pro/services'
    | '/provider/$id'
    | '/service/$id'
    | '/user/bookings'
    | '/user/notifications'
    | '/user/profile'
    | '/user/reviews'
    | '/pro/'
    | '/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  R500Route: typeof R500Route
  LoginRoute: typeof LoginRoute
  ProRoute: typeof ProRouteWithChildren
  ProvidersRoute: typeof ProvidersRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRoute
  UserRoute: typeof UserRouteWithChildren
  ProviderIdRoute: typeof ProviderIdRoute
  ServiceIdRoute: typeof ServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/pro/': {
      id: '/pro/'
      path: '/'
      fullPath: '/pro/'
      preLoaderRoute: typeof ProIndexRouteImport
      parentRoute: typeof ProRoute
    }
    '/user/reviews': {
      id: '/user/reviews'
      path: '/reviews'
      fullPath: '/user/reviews'
      preLoaderRoute: typeof UserReviewsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/notifications': {
      id: '/user/notifications'
      path: '/notifications'
      fullPath: '/user/notifications'
      preLoaderRoute: typeof UserNotificationsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/bookings': {
      id: '/user/bookings'
      path: '/bookings'
      fullPath: '/user/bookings'
      preLoaderRoute: typeof UserBookingsRouteImport
      parentRoute: typeof UserRoute
    }
    '/service/$id': {
      id: '/service/$id'
      path: '/service/$id'
      fullPath: '/service/$id'
      preLoaderRoute: typeof ServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/$id': {
      id: '/provider/$id'
      path: '/provider/$id'
      fullPath: '/provider/$id'
      preLoaderRoute: typeof ProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/services': {
      id: '/pro/services'
      path: '/services'
      fullPath: '/pro/services'
      preLoaderRoute: typeof ProServicesRouteImport
      parentRoute: typeof ProRoute
    }
  }
}

interface ProRouteChildren {
  ProServicesRoute: typeof ProServicesRoute
  ProIndexRoute: typeof ProIndexRoute
}

const ProRouteChildren: ProRouteChildren = {
  ProServicesRoute: ProServicesRoute,
  ProIndexRoute: ProIndexRoute,
}

const ProRouteWithChildren = ProRoute._addFileChildren(ProRouteChildren)

interface UserRouteChildren {
  UserBookingsRoute: typeof UserBookingsRoute
  UserNotificationsRoute: typeof UserNotificationsRoute
  UserProfileRoute: typeof UserProfileRoute
  UserReviewsRoute: typeof UserReviewsRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserBookingsRoute: UserBookingsRoute,
  UserNotificationsRoute: UserNotificationsRoute,
  UserProfileRoute: UserProfileRoute,
  UserReviewsRoute: UserReviewsRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  R500Route: R500Route,
  LoginRoute: LoginRoute,
  ProRoute: ProRouteWithChildren,
  ProvidersRoute: ProvidersRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRoute,
  UserRoute: UserRouteWithChildren,
  ProviderIdRoute: ProviderIdRoute,
  ServiceIdRoute: ServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
